version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  review-apps:
    build: .
    container_name: review-apps
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - VIRTUAL_HOST=overview.apps

  alpha:
    image: tutum/hello-world
    environment:
      - VIRTUAL_HOST=alpha.apps
    labels:
      - url=alpha.apps

  beta:
    image: tutum/hello-world
    environment:
      - VIRTUAL_HOST=beta.apps
    labels:
      - url=beta.apps
